### ISSUE TITLE
auto loot filter is too slow

### ISSUE THREAD

**Issue by prayoga-masagi** [fireundubh/fallout4#18]
i have 2 problem with auto loot : 
1. turn off filter and all item include quest item is moved to sanctuary
2, turn on filter and wait to auto loot works, it so long, after 2 minutes its still not looted
(in some case after 5 minutes its still not looted)

so i have do some research
an items (like junk) in the ground is instantly looted with auto loot 
an items in body/container takes longtime looted with auto loot 

for that i got idea
why not make enemy will drop items on ground if he/she death so them will looted fast
sorry my bad English
thanks for reading

**Comment by fireundubh** [comment]
When you set the auto loot radius too high, all filters will be slow.

When you have all filters enabled, all filters will be slow.

When Filter Mode is set to Any Item, the Bodies and Containers filters will be slow.

When you have any combination of the above, all filters will be extremely slow.

Auto Loot gives you many options, but you have to exercise some care and don't be too greedy.

**Comment by prayoga-masagi** [comment]
i afraid this will be the answer
any way thanks for reply
