### ISSUE TITLE
Auto Loot occasionally freezes the game

### ISSUE THREAD

**Issue by AllRange1337** [fireundubh/fallout4#21]
I don't know exactly when this happens but it occurs quite often. I enabled aoutloot for ammo and junk and set the junk to be send to Sanctuary and ammo to players inventory.

**Comment by fireundubh** [comment]
Auto Loot does not cause crashes or freezes. Auto Loot can exacerbate preexisting issues, such as missing meshes and textures. Report crashes and freezes to Bethesda. Modders can do nothing about them. Also, please search before posting.
