### ISSUE TITLE
Won't loot in combat?

### ISSUE THREAD

**Issue by Xetaxheb** [fireundubh/fallout4#23]
I'm not clear yet whether it affects more than flora, but it doesn't seem to loot if the player is in combat. 
I'm pretty sure a few versions ago it did, but now it doesn't.

**Comment by fireundubh** [comment]
Auto Loot suspends during combat to reduce the load on Papyrus so that it doesn't impact combat itself, particularly if you have any mods that run scripts during combat. The pre-Bethesda.net version also did the same, but I neglected to add those conditions back.

**Comment by Xetaxheb** [comment]
A toggle for that, even disabled by default, would be nice.
