### ISSUE TITLE
Not Looting certain Item.

### ISSUE THREAD

**Issue by LustSinister** [fireundubh/fallout4#26]
So Far I have noticed that Nuka-Cola's aren't being looted. The one's I have found have been in dressers so don't know if that's part of it. Also it says you can loot as much as you want yet in the holo tape it says you can only have 4 filters on at once. (I ended up turning them all on through console command. but is there a way to change this.) I'm new to your mod so sorry if it seems like a noob question. Thanks for your time. 

P.S Also is there an auto loot for weapons/bombs that are laying around?

**Comment by fireundubh** [comment]
> So Far I have noticed that Nuka-Cola's aren't being looted.

All vanilla Nuka-Colas are in the Drinks formlist, which the Drinks filter uses the formlist to find lootable drinks.

Mod-added items are not supported.

>  Also is there an auto loot for weapons/bombs that are laying around?

No. There are no filters for armor and weapons.
