### ISSUE TITLE
I can't get this mod to work at all

### ISSUE THREAD

**Issue by RamenNoodles** [fireundubh/fallout4#31]
I recently got this mod from [here](http://fireundubh.github.io/fallout4/#)

I didn't get the auto loot program when I loaded a save or started a new game.  I tried to add the item through the console but none of the options seem to work or even change in the menu when selected.  After doing a type search I saw there were perks and effects and I assume my character never got them so none of the options work.

**Comment by fireundubh** [comment]
Did you download and install the BA2, too?

**Comment by RamenNoodles** [comment]
This is embarrasing, no I did not.  When I saw that it was required I didn't think it was a download link as well.  I was wondering about it after I hit the download link and only got an .esp

Really sorry about that.
