### ISSUE TITLE
Crash at Museum of Freedom

### ISSUE THREAD

**Issue by Csimbi** [fireundubh/fallout4#33]
Not sure how to tell which version of the plugin I am using; downloaded it today.
Playing 1.7.12 and started a new game.
I get hang (if standing still) or a crash (if moving into range) in the Museum of Freedom, 100% repeatable.
Disable container looting and head down to the security door.
Then, enable the container filter (I have 1024 range, container unlock enabled, 1sec delay and no steal, dunno if these matter).
Wait a moment and game will hang up.
Would it be possible to check it out and fix it?

Also, what tools did you use to create the mod? (So I could try to correct it myself.)

Thanks!

**Comment by fireundubh** [comment]
Mods don't cause crashes; games do. Everything that Auto Loot does uses the same plugins and scripting functions that Bethesda uses. No hacks, no custom DLLs, nothing exotic. There isn't a thing that I can do to help you resolve crash issues.

**Comment by Csimbi** [comment]
That's not entirely true. You might be using uninitialized variables, zero values, etc.
That said, Bethesda should deal with those in the engine itself: instead of crashing, stop the script and log the error .

But, I closed this issue because I found out that the cause was your this plugin (even though the crash occurs 100% on .Activate).

**Comment by fireundubh** [comment]
If you can produce a script that crashes Fallout 4 with uninitialized variables, zero values, etc., I'll believe you, but I've been working with Papyrus for a long, long time and I've never seen such a thing.

Also, `Activate()` has at least one bug that I know of, which Bethesda opted to not fix, so `Activate()` could be broken in other ways.
