### ISSUE TITLE
Improvement recommendations

### ISSUE THREAD

**Issue by Csimbi** [fireundubh/fallout4#35]
Hi,
I've made some changes to the scripts:
 - removed a few redundant checks
 - built in per-loop caps and min. delays for less per-loop load
 - built in random timers to minimize congestion
 - enabled looting in combat

I know that last part is not very lore-friendly, but I don't end up with heaps of bodies and loot around me once the combat is over ( causing a hang).

With this, I can activate all filters and play normally. It will collect items a bit slower though, but that's a trade-off I am happy to make for no crashes.
Game will still crash eventually, but these changes reduced crashes quite a bit.

I'd recommend adopting these changes.
Uploaded here:
https://mab.to/rkufCZMVc

**Comment by rahaney** [comment]
Can you reupload this somewhere to try? Several of us are having issues with the current script - see the open issues. Thanks
