### ISSUE TITLE
Holotape not added to inventory

### ISSUE THREAD

**Issue by Batsegeziech** [fireundubh/fallout4#36]
I just installed the mod and was unable to locate the holotape. I made sure to enable the mod in game as it has a checkmark and everything but it does not show up. If you could give me the Id to spawn it in or something like that id love to know as this mod is something I have wanted forever.

I am playing on the nuka world release.

**Comment by fireundubh** [comment]
Did you download and install the BA2, too?

**Comment by anarchy2351423** [comment]
The holotape does not get added to the inventory with any kind of Alternate Start mods.  Is there a way you can just list the ID code so we can spawn it in if we choose to use alternate starts.

**Comment by Kirmari** [comment]
you can try to use console command (help "auto loot program" 4) to find the id. as the id is bound to you load order then use player.additem (id) 1 . base id may be XX0017AC so XX will be the load order in my case OB0017AC hope it helps

**Comment by frostryder** [comment]
I've been having this exact problem, but find no items when I search... I've searched for "> " (the prefix), loot, program, auto, etc. I'll try add the direct item ID, see if that helps :) Thanks!

**Comment by frostryder** [comment]
No joy, the prefix in my case would be B6, tried that with no luck. Searched for tape with 'help program 4', got the following:  http://steamcommunity.com/sharedfiles/filedetails/?id=802155850

**Comment by frostryder** [comment]
Tried to force completion of MQ102, didn't help with getting the notes. Had some other issues, had to restart playthru, so did it without Alternate Start. Worked perfectly, of course lol

**Comment by hahnehome** [comment]
I cant seem to get it to work either.
